name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/813885317674/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-service-account@concrete-flight-383716.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'deadfellaz-pixel'
        runtime: 'python39'
        entry_point: 'sprite_sheet_to_gif'
        source_dir: './'
